package nl.ipo.cds.etl.process;

public enum HarvesterMessageKey {
	HARVESTER,
	
	PGR_ROOT, 
	PGR_HTTP_ERROR,
	PGR_EXCEPTION,
	METADATA, 
	METADATA_NOT_FOUND, 
	METADATA_NOT_FOUND_ERROR, 
	METADATA_DATE, 
	METADATA_DATEFORMAT, 
	METADATA_WFSURL, 
	METADATA_XSDURL, 
	METADATA_FEATURETYPE, 
	METADATA_CAPABILITIES_HTTP_ERROR,
	METADATA_CAPABILITIES_EXCEPTION,
	METADATA_CAPABILITIES_WFSURL,
	
	METADATA_FEATURETYPE_HTTP_ERROR,
	METADATA_FEATURETYPE_NOT_FOUND,
	METADATA_FEATURETYPE_INVALID,
	
	METADATA_INVALID_IDENTIFIER
}